apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-time-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-time-app
  template:
    metadata:
      labels:
        app: sample-time-app
    spec:
      containers:
        - name: sample-time-app
          image: docker.io/leonchai/sample-time-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /time
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sample-time-app
spec:
  type: NodePort
  selector:
    app: sample-time-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
